name: Main Branch Pipeline

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Tests
    uses: './.github/workflows/tests.yml'
  sonar-scan:
    needs: tests
    uses: './.github/workflows/sonar.yml'
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}
