name: Main Branch Pipeline

on:
  push:
    branches:
      - main

jobs:
  validation:
    name: Code Validation
    uses: './.github/workflows/validate_code.yml'
  tests:
    name: Tests
    uses: './.github/workflows/tests.yml'
  sonar-scan:
    needs: [tests, validation]
    uses: './.github/workflows/sonar.yml'
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}